### ISSUE TITLE
"It works!"  Congratulations!

### ISSUE THREAD

**Issue by PySimpleGUI** [vix597/chevy-volt-trip-mode#1]
![image](https://user-images.githubusercontent.com/46163555/141604502-74054d6a-50fc-44e6-a073-7059300f9ee0.png)

I love seeing  

![image](https://user-images.githubusercontent.com/46163555/141604522-941f9070-9972-415e-a231-b04ea8978720.png)

somewhere on a project!

**Comment by laplante-sean** [comment]
Haha yeah, `PySimpleGUI` ended up working out great for what I needed. Still going to be tweaking it a bit but it worked with 0 headache. Also great job on the error messages. I tried to call `maximize` and got an error message that told me exactly how to fix it right in the GUI (e.g. pass `finalize=True` or call `finalize()` before `maximize`).
